name: netcalc
version: '3.2'
summary: Simple network calculator
description: |
  A program that converts values from the IP address and prefix of the subnet mask.
  It has the ability to download data from the interface.
  It calculates values for the subnet mask, network address,
  broadcast address, first and last address and number of hosts.
grade: stable
base: core20
confinement: strict
license: GPL-2.0

apps:
  netcalc:
    command: netcalc
    plugs:
      - network-bind

parts:
  netcalc:
    plugin: cmake
    source: .
    build-packages:
      - cmake
      - make
      - pkg-config
    stage-packages:
      - libgtk-3-dev
