#!/bin/sh

if [ -e /usr/local/bin/netcalc ] ; then
    rm /usr/local/bin/netcalc
    echo "Removed netcalc"
fi

if [ -e /usr/share/applications/netcalc.desktop ] ; then
    rm /usr/share/applications/netcalc.desktop
    echo "Removed netcalc.desktop file"
fi

if [ -e /usr/share/icons/hicolor/128x128/apps/netcalc-128x128.png ] ; then
    rm /usr/share/icons/hicolor/128x128/apps/netcalc-128x128.png
    echo "Removed netcalc-128x128.png file"
fi